In [1]:
## Khai báo thư viện pytorch
import torch

In [2]:
# Kiểm tra phiên bản pytorch
torch.__version__

'1.6.0+cu101'

In [3]:
# Kiểm tra cuda có tồn tại
torch.cuda.is_available()

True

In [4]:
# Kiểm tra phiên bản cuda
torch.version.cuda

'10.1'

##### Using CUDA With PyTorch

In [5]:
t = torch.tensor([1,2,3])

In [6]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

In [7]:
import numpy as np

a = [1,2,3,4]

In [8]:
a[2]

3

In [9]:
dd = [[1,2,3],
      [4,5,6],
      [7,8,9]]

In [10]:
dd[0][2]

3

In [11]:
# Tạo một tensor
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
# Trả về kiểu của t
type(t)

torch.Tensor

In [13]:
# Trả về kích thước của t 
t.shape

torch.Size([3, 3])

In [14]:
# Chuyển t về ma trận 1*9
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
# Kiểm tra kiểu dữ liệu của các phần tử trong t
t.dtype

torch.int64

In [16]:
# chỉ định thiết bị (CPU hoặc GPU) nơi dữ liệu của tensor được phân bổ. Điều này xác định nơi tính toán tensor cho tensor đã cho sẽ được thực hiện
t.device

device(type='cpu')

In [17]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [18]:
# chỉ định cách tensor được lưu trữ trong bộ nhớ.
t.layout

torch.strided

#### Creating Tensors Using Data

In [19]:
data = np.array([1,2,3])

In [20]:
# Có 4 cách để tạo tensors
o1 = torch.Tensor(data)
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)
o4 = torch.from_numpy(data)

In [21]:
print(o1) 
print(o2)
print(o3)
print(o4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [22]:
# Tạo ma trận đơn vị 2*2
print(torch.eye(2))

tensor([[1., 0.],
        [0., 1.]])


In [23]:
# Tạo ma trận toàn 0 kích thước 2*2
print(torch.zeros([2,2]))

tensor([[0., 0.],
        [0., 0.]])


In [24]:
# Tạo ma trận toàn 0 kích thước 2*2
print(torch.ones([2,2]))

tensor([[1., 1.],
        [1., 1.]])


In [25]:
# Tạo ma trân 2*2 ngẫu nhiên trong khoảng [0,1]
print(torch.rand([2,2]))

tensor([[0.6092, 0.3938],
        [0.3917, 0.1880]])


In [26]:
print(o1.dtype) # dtype mặc định sẽ là torch.float32
print(o2.dtype)
print(o3.dtype)
print(o4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [27]:
torch.get_default_dtype()

torch.float32

In [28]:
# torch.Tensor() and torch.tensor() copy their input data while 
# torch.as_tensor() and torch.from_numpy() share their input data in memory with the original input object.
print('old:', data)

old: [1 2 3]


In [29]:
data[0] = 0

In [30]:
print('new:', data)

new: [0 2 3]


In [31]:
print(o1)
print(o2)
print(o3)
print(o4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 2, 3], dtype=torch.int32)
tensor([0, 2, 3], dtype=torch.int32)
