In [1]:
import torch

### Tensor Reduction Operations

##### Reduction Operation Example

In [2]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [3]:
t.sum()

tensor(8.)

In [4]:
t.numel()

9

In [5]:
t.sum().numel()

1

##### Common Tensor Reduction Operations

In [6]:
t.prod()

tensor(0.)

In [7]:
t.mean()

tensor(0.8889)

In [8]:
t.std()

tensor(1.1667)

##### Reducing Tensors By Axes

In [9]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [10]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [11]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

##### Understanding Reductions By Axes

In [12]:
t[0].sum()

tensor(4.)

In [13]:
t[1].sum()

tensor(8.)

##### Argmax Tensor Reduction Operation

In [14]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [15]:
t.max()

tensor(5.)

In [16]:
t.argmax()

tensor(11)

In [17]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [18]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [19]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [20]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [21]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

### Accessing Elements Inside Tensors

In [22]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)


In [23]:
t.mean()

tensor(5.)

In [24]:
t.mean().item()

5.0

In [25]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [26]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)